"""Add Notices and extra fields to AllowedRollNumber

Revision ID: 5927230d097f
Revises: 4f5c961c425f
Create Date: 2026-07-02 03:26:59.648598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5927230d097f'
down_revision: Union[str, Sequence[str], None] = '4f5c961c425f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allowed_roll_numbers', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('allowed_roll_numbers', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('allowed_roll_numbers', sa.Column('room_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('allowed_roll_numbers', 'room_number')
    op.drop_column('allowed_roll_numbers', 'email')
    op.drop_column('allowed_roll_numbers', 'name')
    # ### end Alembic commands ###
