"""Add setup_code to allowed_roll_numbers

Revision ID: a8db691a0b26
Revises: cbd91f282d64
Create Date: 2026-07-03 10:05:50.542499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8db691a0b26'
down_revision: Union[str, Sequence[str], None] = 'cbd91f282d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allowed_roll_numbers', sa.Column('setup_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('allowed_roll_numbers', 'setup_code')
    # ### end Alembic commands ###
