"""Add roll_no to User

Revision ID: cbd91f282d64
Revises: 3ae5dc679601
Create Date: 2026-07-02 10:41:04.028902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd91f282d64'
down_revision: Union[str, Sequence[str], None] = '3ae5dc679601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roll_no', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'roll_no')
    # ### end Alembic commands ###
